---
label: Service
hide_body: false
fields:
- type: number
  name: ordre
  label: ordre
- type: text
  name: titre
  label: titre
- type: text
  name: description
  label: description
- name: illustration
  type: file
  config:
    maxSize: 64
  label: Image
pages:
- _services/Coaching Individuel.md
- _services/Coaching Professionel.md
- _services/Coaching Sportif HN.md
