# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
# File: .github/workflows/repo-sync.yml

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      if: ${{secrets.PAT != null }}
      with:
        source_repo: "https://${{secrets.PAT}}@github.com/william-kandot/cmental-forrest.git"
        source_branch: "master"
        destination_repo: "https://${{secrets.PAT}}@github.com/serialberry/cmental.git"
        destination_branch: "master"
